packages:
  - 'packages/build-v3*'
  - 'examples/vue3-demo*'
  - '!examples/vue2-demo'
  - '!packages/build-v2'
  # - 'examples/vue2-demo*'
  # - 'packages/build-v2*'
  # - '!examples/vue3-demo'
  # - '!packages/build-v3'
  # - 'packages*'
  # - 'dev-temp*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - 'core-js'
  - 'esbuild'
  - 'vue-demi'
